beam_icon = """
    /* XPM */
    static char *_0ddddfe6a2d42f3d616a62ec3bb0f7c8Jp52mHVQRFtBmFY[] = {
    /* columns rows colors chars-per-pixel */
    "16 16 6 1 ",
    "  c #ED1C24",
    ". c #ED5C5E",
    "X c #ED9092",
    "o c #EDBDBD",
    "O c #EDDFDF",
    "+ c None",
    /* pixels */
    "+++++++++..XooOO",
    "++++++..+..XXooO",
    "++++++++++. XXoo",
    "+++++++.++  .XXo",
    "++++++.++  .  XX",
    "++++++++  .  ..X",
    "+++++++  .  ++..",
    "++++++  .  +++++",
    "+++++  .  ++.+.+",
    "++++  .  ++.++.+",
    "+++  .  ++++++++",
    "++  .  +++++++++",
    "+  .  ++++++++++",
    "  .  +++++++++++",
    " .  ++++++++++++",
    ".  +++++++++++++"
    };
    """

optic_icon = """
/* XPM */
static char *_bdb90c773a846ffe937e07621744845Gx0agqycnxSkD4MV[] = {
/* columns rows colors chars-per-pixel */
"64 64 52 1 ",
"  c #23232C",
". c #2C2C2F",
"X c #262633",
"o c #2D2D33",
"O c #2C2C3C",
"+ c #353535",
"@ c #34343B",
"# c None",
"$ c #2E2F40",
"% c #333345",
"& c #373843",
"* c #393944",
"= c #35354B",
"- c #37384F",
"; c #3C3C4C",
": c #3C3C53",
"> c #3E3E59",
", c #3F405C",
"< c #414156",
"1 c #42435D",
"2 c #444563",
"3 c #484865",
"4 c #474869",
"5 c #4A4A6C",
"6 c #4B4C70",
"7 c #4D4E73",
"8 c #4E4F74",
"9 c #4F5076",
"0 c #505077",
"q c #53537B",
"w c #54547B",
"e c #53547C",
"r c #55567F",
"t c #555680",
"y c #575882",
"u c #585883",
"i c #595985",
"p c #5B5B88",
"a c #5B5C8A",
"s c #5C5C8A",
"d c #5F5F8F",
"f c #5F608F",
"g c #5F6090",
"h c #606091",
"j c #626395",
"k c #636497",
"l c #646497",
"z c #646598",
"x c #67679C",
"c c #67689D",
"v c #68699E",
"b c #696AA0",
/* pixels */
"################################################################",
"################################################################",
"################################################################",
"################################################################",
"################################################################",
"############################+o...+##############################",
"#########################+oO$OOOX  ..++#########################",
"#######################+@::::==%%O=27rr72;+#####################",
"######################@>21,,>>:%4dllllllllp<+###################",
"#####################&4444422:2hllllllllllllr@##################",
"###################+:7776555>qlllllllllllllllh*#################",
"###################:qqq09871slllllllllllllllllh*################",
"##################;trrreqq1dllllllllllllllllllld+###############",
"#################&iiuyttt2dlllllllllllllllllllllq+##############",
"################+rapiiii5ulllllllllllllllllllllll:##############",
"################4dddssar7lllllllllllllllllllllllls+#############",
"###############;hgfdddd4llllllllllllllllllllllllll<#############",
"##############+rhhhhhh7sllllllllllllllllllllllllllu+############",
"##############:kkjjjjh5llllllllllllllllllllllllllll*############",
"##############rzzllkk7hllllllllllllllllllllllllllll2############",
"#############*zzzzzzk5lllllllllllllllllllllllllllllr############",
"#############5xxzzzzqhlllllllllllllllllllllllllllllj+###########",
"############+jvccccx7lllllllllllllllllllllllllllllll*###########",
"############;vvvvvvhqlllllllllllllllllllllllllllllll<###########",
"############4vvvvvv0llllllllllllllllllllllllllllllll2###########",
"###########+sbbbvvv7llllllllllllllllllllllllllllllll4###########",
"###########+vbbbbbc7llllllllllllllllllllllllllllllll7###########",
"###########;bbbbbbidllllllllllllllllllllllllllllllll0###########",
"###########1bbbbbb0lllllllllllllllllllllllllllllllll0###########",
"###########4bbbbbb0lllllllllllllllllllllllllllllllll7###########",
"###########7vvvvvb8lllllllllllllllllllllllllllllllll4###########",
"###########rvvvvvv7lllllllllllllllllllllllllllllllll3###########",
"##########+icvvvvc7lllllllllllllllllllllllllllllllll1###########",
"##########+ixccccl0lllllllllllllllllllllllllllllllll;###########",
"##########+izzzzzhrlllllllllllllllllllllllllllllllll@###########",
"###########tzzzzzdrlllllllllllllllllllllllllllllllld+###########",
"###########0klllzfwllllllllllllllllllllllllllllllll0############",
"###########4jjjjkh0llllllllllllllllllllllllllllllll1############",
"###########1hhhhhh7llllllllllllllllllllllllllllllll&############",
"###########:ddfghh5llllllllllllllllllllllllllllllli+############",
"###########&sddddd5lllllllllllllllllllllllllllllll1#############",
"###########+ypaass5llllllllllllllllllllllllllllllj+#############",
"############4iiiii4jlllllllllllllllllllllllllllll7##############",
"############;tttyurqlllllllllllllllllllllllllllll*##############",
"############+qerrrt4llllllllllllllllllllllllllll0###############",
"#############:0qqqq2lllllllllllllllllllllllllllj&###############",
"#############+7778950llllllllllllllllllllllllll3################",
"##############-555672llllllllllllllllllllllllli+################",
"##############+144442ekllllllllllllllllllllllj&#################",
"###############@11222:jllllllllllllllllllllll:##################",
"################@:>>>>4lllllllllllllllllllll2###################",
"#################O=-::=0lllllllllllllllllll2+###################",
"##################oO%%=%rllllllllllllllllj<#####################",
"###################+ XOOO7lllllllllllllli*######################",
"#####################o    :dllllllllllh1+#######################",
"########################++o.<rjlllljw1+#########################",
"##############################+*;;&+############################",
"################################################################",
"################################################################",
"################################################################",
"################################################################",
"################################################################",
"################################################################",
"################################################################"
};

"""

thorlabs_icon = """
    /* XPM */
    static char *_e94ebdf19f64588ceeb5b5397743c6amoxjrynTrPg9Fk5U[] = {
    /* columns rows colors chars-per-pixel */
    "16 16 2 1 ",
    "  c None",
    "& c red",
    /* pixels */
    "                ",
    "  &&&&&&&&&&&&  ",
    "  &&&&&&&&&&&&  ",
    "  &&&&&&&&&&&&  ",
    "  &&&&&&&&&&&&  ",
    "      &&&&      ",
    "      &&&&      ",
    "      &&&&      ",
    "      &&&&      ",
    "      &&&&      ",
    "      &&&&      ",
    "      &&&&      ",
    "      &&&&      ",
    "      &&&&      ",
    "      &&&&      ",
    "                "
    };
    """
